Updating time section
sunpy/sunpy-1.0-paper pull request #125
Opened 2019-07-31 01:48 UTC by hayesla

In this PR I tried to address Issue #99 

I'm not too sure if its exhaustive but tried to hit on the points of what astropy.time offers and why it is used. I've also updated the reference to 'high precision time format' and 'modern astronomical time format' to just 'specific scientific time class'.

2019-08-02 13:20 UTC, ehsteve commented on sections/8-units.tex
> +Furthermore the adoption of the \package{astropy.time} within \sunpypkg provides the necessary support for leap seconds, light travel calculations, and high precision time representation.
Do you want to add something about being able to accurately compare the timing of solar events to astrophysical events? I'm not sure what the use case would be. Maybe being able to accurately track solar events through the solar system compared to planetary bodies or accurately compare inputs to the Earth's magnetosphere by solar and extra solar events? Another one might be to be able to differentiate events in x-ray data that are solar compared to those that are extra-solar like pulsar bursts.

2019-08-02 13:21 UTC, ehsteve requested changes
One suggestion to add example for solar and astro to use the same high-precision time format so that events can be compared.

2019-08-05 20:34 UTC, hayesla commented
i've now updated the text to make reference to this, however I have not actually included a use-case example - I'm not too sure of one! How do you think it reads now?

2019-08-05 20:35 UTC, hayesla commented
ping @ehsteve @ayshih

2019-08-06 18:13 UTC, ehsteve approved these changes

2019-08-06 18:13 UTC, merged